### ISSUE TITLE
Streetname, streetnumber, zip and city

### ISSUE THREAD

**Issue by TimFoerster** [Hambern/octobercms.company#10]
Hello,

a lot of themes uses different rows for displaying the address. 
I would suggest to change the address field to streetname, streetnumber, zip and city.
This makes it easier to integrate this plugin into frontend themes.

Thanks

**Comment by hambern** [comment]
Ah. You're right. Will fix this, but keep address as an attribute

**Comment by TimFoerster** [comment]
Thanks
