### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by tjaynl** [Hambern/octobercms.company#21]
So i'm trying to install the plugin but it doesn't want to install it gives me this error message:

"SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'link' (SQL: alter table `hambern_company_services` add `link` varchar(255) null)" on line 664 of /home/usr/url/vendor/laravel/framework/src/Illuminate/Database/Connection.php

**Comment by hambern** [comment]
It tries to recreate the link column when it already exists. I can look into this tomorrow. Sorry for the issue

**Comment by tjaynl** [comment]
No problem thanks for the quick reply, maybe some usefull information:
Build version: 455

**Comment by tjaynl** [comment]
it seems that if you delete the "link" table from hambern_company_services that it makes it installable and working
