### ISSUE TITLE
Company api

### ISSUE THREAD

**Issue by ribsousa** [Hambern/octobercms.company#3]
company data can be returned by api?

**Comment by ametad** [comment]
You should make your own API endpoint, but then yes you can show Company data (as JSON). 

Per example, add the Employees component to a page and at the page only print::

```
{{ employees }}
```

**Comment by hambern** [comment]
It should actually be even better to just add the Component to the page and not pick a layout. In that way you get a correct json-response like this: `{% component 'Employees' %}` Then the default-code makes this automatically:

```
{{ __SELF__.employee.toJson }}
{{ __SELF__.employees.toJson }}
```
