### ISSUE TITLE
Logo image selected with mediafinder is not saved

### ISSUE THREAD

**Issue by ametad** [Hambern/octobercms.company#4]
At the settings page of the Company plugin a logo image can be selected with the mediafinder. I noticed this new feature and I think it is a good choice btw!

Problem: the selected logo image is not being saved as part of the settings.

Reproduce:
- At the settings page of Company click at the 'Logotype', the mediafinder is being opened
- Optionally upload a file
- Select the image you want and hit Insert / Crop & Insert
- The selected image is visible at the settings page
- Do a reload of the settings page
- There is no image selected anymore (!) . The rest of settings are correctly just as you saved them.

I am looking at this now, if I find the problem I let you know.

**Comment by hambern** [comment]
Reverted back to the file upload again. A bigger update with media finder and filters in the backend will come eventually :)

**Comment by ametad** [comment]
Thank you for the heads up!

The most recent 1.3.x version has this mediafinder already implemented. Do you mean that there will be a version at the OC market reverted back to the upload type? When are you planning to push that to the OC market?

**Comment by ametad** [comment]
Oh, I see:

1.3.5  
!!! Due to a bug the logo-field is now once again a fileupload. Sorry for this.
Sep 30, 2016

**Comment by hambern** [comment]
Now the entire plugin once again uses fileupload. And it's pushed to the marketplace together with an excuse :) The media finder implementation weren't that well thought out. I think I will make a total switch to the media finder, and try to make it a choice in the settings: if you want to use the file upload or the media finder. That way it won't bother those who doesn't want the file handling switch.

👍
