### ISSUE TITLE
How to loop through pictures in Gallery

### ISSUE THREAD

**Issue by ujackson** [Hambern/octobercms.company#7]
How do you loop through pictures in a single gallery. It doesn't seem to work.

**Comment by hambern** [comment]
This should work:
```
{% for picture in gallery.pictures %}
    <img class="picture" src="{{ picture.thumb(700,700,'crop') }}">
{% endfor %}
```

Tried that? I have made several webpages with this, and they still work

**Comment by ujackson** [comment]
Thanks alot

**Comment by hambern** [comment]
No problems :) glad to help
