### ISSUE TITLE
Can't get project.tags to work properly in my theme.

### ISSUE THREAD

**Issue by tjaynl** [Hambern/octobercms.company#9]
Let me start with thanking you for making this plugin free to use.

But i have a small problem with getting {{ projects.tags }} to work on my page because it gives me a raw output, and i can't find anything in the documentation on how to get it to work. I want to be able to get every tag element an set it in an list tag.

**Comment by hambern** [comment]
Try looping them:

{% for tag in project.tags %}
{% endfor %}

**Comment by tjaynl** [comment]
Thanks for the quick reply, but unfortunately it still gives me the raw output like this:

[{"id":"1","name":"Webdesign","description":"","icon":"fa-paint-brush","published_at":"2017-02-19 00:00:00","created_at":"2017-02-19 08:36:23","updated_at":"2017-02-19 08:36:23","pivot":{"project_id":"1","tag_id":"1"}},{"id":"2","name":"CMS","description":"","icon":"fa-wrench","published_at":"2017-02-19 00:00:00","created_at":"2017-02-19 08:51:53","updated_at":"2017-02-19 08:51:53","pivot":{"project_id":"1","tag_id":"2"}}] [{"id":"1","name":"Webdesign","description":"","icon":"fa-paint-brush","published_at":"2017-02-19 00:00:00","created_at":"2017-02-19 08:36:23","updated_at":"2017-02-19 08:36:23","pivot":{"project_id":"1","tag_id":"1"}},{"id":"2","name":"CMS","description":"","icon":"fa-wrench","published_at":"2017-02-19 00:00:00","created_at":"2017-02-19 08:51:53","updated_at":"2017-02-19 08:51:53","pivot":{"project_id":"1","tag_id":"2"}}]

The code i'm using is:

{% for tag in project.tags %}
{{ project.tags }}
{% endfor %}

**Comment by hambern** [comment]
Perfect. Thats the defaitism json output for eloquent objects. Try this:

'''
{% for tag in project.tags %}
<i class="fa {{ tag.icon }}"></i>
{{ tag.name }}
{% endfor %}
'''

**Comment by hambern** [comment]
Hmmm

{% for tag in project.tags %}
    <i class="fa {{ tag.icon}}"><>
    {{ tag.name }}
{% endfor %}

**Comment by hambern** [comment]
Seems like the HTML tag doesn't work. See if you can get it to work. You have to access the tag objects attributes {{ tag.name }}. For the name {{ tag.icon }} for the icon string

**Comment by tjaynl** [comment]
This did the trick.
Thank you very much for the help 👍

P.S. Might be useful to add this to the documentation.
